### ISSUE TITLE
Missing notifications in js version

### ISSUE THREAD

**Issue by c0d3m4st4** [xvortex/ps4-dumper#8]
Hello.

Am i missing something here ? 

Notifications are missing when launching it self hosted (html + js files in a web server).

Notifications are shown fine when binary payload sent. Also shown in some beta 1 version floating around.

bin and js payloads are exactly the same.

Thanks.

**Comment by itzxzac** [comment]
This has been an issue since 4.55 dropped. The only way to get it to work from my experience is to inject the .bin file. I wonder if xvortex has left the scene.

**Comment by c0d3m4st4** [comment]
Awesome, thanks!
